/* ORDENANDO PELO NOME */

-- CRESCENTE
SELECT * FROM Clientes
ORDER BY Nome -- ALT

-- DECRESCENTE
SELECT * FROM Clientes
ORDER BY Nome DESC


/* ORDENANDO PELO NOME E SOBRENOME */

-- CRESCENTE
SELECT * FROM Clientes
ORDER BY Nome, Sobrenome -- ALT

-- DECRESCENTE
SELECT * FROM Clientes
ORDER BY Nome DESC, Sobrenome DESC